name: AI Code Reviewer

on:
  pull_request:
    types:
      - opened
      - synchronize
permissions: write-all
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: AI Code Reviewer
        uses: never112/ai-code-reviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.MINIMAX_KEY }}
          OPENAI_API_BASE_URL: ${{ secrets.MINIMAX_OPENAPI_BASEURL }}
          OPENAI_API_MODEL: "MiniMax-M2.7"
          exclude: "**/*.json, **/*.md"
